config/routes.rb
Muzik::Application.routes.draw do

  resources :holiday_song_periods

  resources :media_players do
    collection do
      get 'datatable'
      get 'delete'
      get 'location_info'
      get 'songs_library'
      get 'blacklisted_songs'
      get 'playlists'
    end
  end

  resources :dashboard

  resources :playlists do
    collection do
      get 'display'
      get 'fetch'
    end
  end

  resources :energy_levels
  resources :energy_level_intervals

  resources :energy_level_wizard do
    collection do
      post 'add_energy_level_interval'
      post 'update_energy_level_intervals'
    end
  end

  resources :locations, :shallow => true do
    collection do
      get 'datatable'
      get 'delete'
      get 'blacklist_songs'
      post 'refresh_energy_level_intervals'
      get 'energy_level_intervals'
      get 'schedules'
    end
    resources :schedules
  end

  resources :black_lists do
    collection do
      get 'fetch'
    end
  end

  resources :group_song_assignments do
    collection do
      get 'upload_itunes_plist'
      post 'upload_itunes_plist'
    end
  end

  resources :song_libraries

  resources :groups do
    collection do
      get 'datatable'
      get 'remove_location'
      post 'add_location'
      get 'delete'
      get 'playlists'
      get 'songstable'
      get 'songs'
      get 'remove_group_song_assignment'
    end
  end

  resources :songs do
    collection do
      get 'upload'
      get 'datatable'
      get 'datatable2'
      get 'autocomplete_song_title'
      post 'add_tag'
    end
  end

  resources :taggings
  resources :tests

  root :to => 'dashboard#index'

end

app/models/group_song_assignment.rb
class GroupSongAssignment < ActiveRecord::Base
#  validates_uniqueness_of :song_id, :scope => :group_id
  belongs_to :song
  belongs_to :group
  belongs_to :energy_level
end

app/controllers/group_song_assignments_controller.rb
class GroupSongAssignmentsController < ApplicationController
  # GET /group_song_assignments
  # GET /group_song_assignments.json
  def index
    @group_song_assignments = GroupSongAssignment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @group_song_assignments }
    end
  end

  # GET /group_song_assignments/1
  # GET /group_song_assignments/1.json
  def show
    @group_song_assignment = GroupSongAssignment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @group_song_assignment }
    end
  end

  # GET /group_song_assignments/new
  # GET /group_song_assignments/new.json
  def new
    @group_song_assignment = GroupSongAssignment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @group_song_assignment }
    end
  end

  # GET /group_song_assignments/1/edit
  def edit
    @group_song_assignment = GroupSongAssignment.find(params[:id])
  end

  # POST /group_song_assignments
  # POST /group_song_assignments.json
  def create
    @group_song_assignment = GroupSongAssignment.new(params[:group_song_assignment])

    respond_to do |format|
      if @group_song_assignment.save
        format.html {
          if request.env["HTTP_REFERER"].include? "groups"
            redirect_to @group_song_assignment.group
          else
            redirect_to @group_song_assignment, :notice => 'Group song assignment was successfully created.'
          end
        }
        format.js {
          if request.env["HTTP_REFERER"].include? "groups"
            @group = @group_song_assignment.group
            render "/groups/update_songtable"
          end
        }
        format.json {
          render:json => @group_song_assignment, :status => :created, :location => @group_song_assignment
        }
      else
        format.html { render :action => "new" }
        format.json { render :json => @group_song_assignment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /group_song_assignments/1
  # PUT /group_song_assignments/1.json
  def update
    @group_song_assignment = GroupSongAssignment.find(params[:id])

    respond_to do |format|
      if @group_song_assignment.update_attributes(params[:group_song_assignment])
        format.html { redirect_to @group_song_assignment, :notice => 'Group song assignment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @group_song_assignment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /group_song_assignments/1
  # DELETE /group_song_assignments/1.json
  def destroy
    @group_song_assignment = GroupSongAssignment.find(params[:id])
    @group_song_assignment.destroy

    respond_to do |format|
      format.html { redirect_to group_song_assignments_url }
      format.json { head :ok }
    end
  end

  def upload_itunes_plist
    return if !params[:group_song_assignment]

    songs = parse_itunes_plist(params[:group_song_assignment][:uploaded_itunes_plist])

    tmp = parse_itunes_plist_filename(params[:group_song_assignment][:uploaded_itunes_plist].original_filename)
    group_name = tmp[:client]

    energy_level = EnergyLevel.where(:name => tmp[:energy_level]).first
    group = Group.where(:name => group_name).first
    assign_songs_to_group(songs, group, energy_level)
    flash[:notice] = 'Songs list was successfully uploaded.'
  end

  private
  def parse_itunes_plist_filename(filename)
    result = {}
    tokens = filename.split('.')
    if tokens.size != 6
      result[:error] = "Invalid filename standard. Unable to figure out client name and energy level"
      return result
    end

    result[:client] = tokens[1]
    result[:energy_level] = tokens[4]
    result
  end

  def parse_itunes_plist(itunes_plist)
    Tpg::ItunesPlistParser::parse(itunes_plist)
  end

  # TODO: need to worry about ACID properties
  # TODO: check return statuses of method calls
  def assign_songs_to_group(songs_list, group, energy_level)
    gsas = []
    songs_list.each do |song_hash|
      song = Song.where(:itunes_persistent_id => song_hash['Persistent ID']).first
      # Create song if it's not there
      if song.nil?
        song = create_song(song_hash)
      end

      gsas << GroupSongAssignment.new(:song_id => song.id, :group_id => group.id, :energy_level_id => energy_level.id)
    end

    # Delete old song assignment (only delete the one of the same energy level)
    group.group_song_assignments.where(:energy_level_id => energy_level.id).delete_all

    # Create group_song_assignments. This will also blow out the old assignments
    # TODO: figure out how to mass delete and mass insert to speed things up
    gsas.each do |gsa|
      group.group_song_assignments << gsa
    end
  end

  def create_song(song_hash)
    artist = song_hash['Artist']
    album = song_hash['Album']
    title = song_hash['Name']

    artist = "MISSING" if artist.nil? or artist.empty?
    album = "MISSING" if album.nil? or album.empty?
    title = "MISSING" if title.nil? or title.empty?

    filename = "#{Tpg::Utils::md5_from_meta([title, artist, album])}.mp3"
    Song.create(:title => title,
                :belongs_to_album => album,
                :artist => artist,
                :itunes_persistent_id => song_hash['Persistent ID'],
                :duration => song_hash['Total Time'].to_i / 1000,
                :file_path => filename)
  end
end

app/helpers/group_song_assignments_helper.rb
module GroupSongAssignmentsHelper
end

app/views/group_song_assignments/_form.html.erb
<%= form_for(@group_song_assignment) do |f| %>
  <% if @group_song_assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_song_assignment.errors.count, "error") %> prohibited this group_song_assignment from being saved:</h2>

      <ul>
      <% @group_song_assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :song_id %><br />
    <%= f.number_field :song_id %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.number_field :group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/group_song_assignments/edit.html.erb
<h1>Editing group_song_assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_song_assignment %> |
<%= link_to 'Back', group_song_assignments_path %>

app/views/group_song_assignments/index.html.erb
<h1>Listing group_song_assignments</h1>

<table>
  <tr>
    <th>Song</th>
    <th>Group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @group_song_assignments.each do |group_song_assignment| %>
  <tr>
    <td><%= group_song_assignment.song_id %></td>
    <td><%= group_song_assignment.group_id %></td>
    <td><%= link_to 'Show', group_song_assignment %></td>
    <td><%= link_to 'Edit', edit_group_song_assignment_path(group_song_assignment) %></td>
    <td><%= link_to 'Destroy', group_song_assignment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group song assignment', new_group_song_assignment_path %>

app/views/group_song_assignments/new.html.erb
<h1>New group_song_assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', group_song_assignments_path %>

app/views/group_song_assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Song:</b>
  <%= @group_song_assignment.song_id %>
</p>

<p>
  <b>Group:</b>
  <%= @group_song_assignment.group_id %>
</p>


<%= link_to 'Edit', edit_group_song_assignment_path(@group_song_assignment) %> |
<%= link_to 'Back', group_song_assignments_path %>

app/views/group_song_assignments/upload_itunes_plist.html.erb
<h3>Upload Group Songs List</h3>

<%= form_for(:group_song_assignment, :url => {:action => 'upload_itunes_plist'},:html => { :multipart => true }) do |form| %>
  <div>
    Energy Level (Optional):
    <%= form.select :energy_level_id, EnergyLevel.order('elevel').collect{|e| [ "#{e.name}(#{e.elevel})", e.id]}, { :include_blank => true} %>
  </div>
  <div>
    Group (Optional):
    <%= form.select :group_id, Group.order('name').collect{|e| [ e.name, e.id]}, { :include_blank => true} %>
  </div>
  Upload client playlist: <%= form.file_field("uploaded_itunes_plist") %><br/>
  <%= submit_tag("Upload file") %> 
<% end %>