config/routes.rb
Muzik::Application.routes.draw do

  resources :holiday_song_periods

  resources :media_players do
    collection do
      get 'datatable'
      get 'delete'
      get 'location_info'
      get 'songs_library'
      get 'blacklisted_songs'
      get 'playlists'
    end
  end

  resources :dashboard

  resources :playlists do
    collection do
      get 'display'
      get 'fetch'
    end
  end

  resources :energy_levels
  resources :energy_level_intervals

  resources :energy_level_wizard do
    collection do
      post 'add_energy_level_interval'
      post 'update_energy_level_intervals'
    end
  end

  resources :locations, :shallow => true do
    collection do
      get 'datatable'
      get 'delete'
      get 'blacklist_songs'
      post 'refresh_energy_level_intervals'
      get 'energy_level_intervals'
      get 'schedules'
    end
    resources :schedules
  end

  resources :black_lists do
    collection do
      get 'fetch'
    end
  end

  resources :group_song_assignments do
    collection do
      get 'upload_itunes_plist'
      post 'upload_itunes_plist'
    end
  end

  resources :song_libraries

  resources :groups do
    collection do
      get 'datatable'
      get 'remove_location'
      post 'add_location'
      get 'delete'
      get 'playlists'
      get 'songstable'
      get 'songs'
      get 'remove_group_song_assignment'
    end
  end

  resources :songs do
    collection do
      get 'upload'
      get 'datatable'
      get 'datatable2'
      get 'autocomplete_song_title'
      post 'add_tag'
    end
  end

  resources :taggings
  resources :tests

  root :to => 'dashboard#index'

end

app/models/black_list.rb
class BlackList < ActiveRecord::Base
  belongs_to :location
  belongs_to :song
end

app/controllers/black_lists_controller.rb
class BlackListsController < ApplicationController
  # GET /black_lists
  # GET /black_lists.json
  def index
    @black_lists = BlackList.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @black_lists }
    end
  end

  # GET /black_lists/1
  # GET /black_lists/1.json
  def show
    @black_list = BlackList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @black_list }
    end
  end

  # GET /black_lists/new
  # GET /black_lists/new.json
  def new
    @black_list = BlackList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @black_list }
    end
  end

  # GET /black_lists/1/edit
  def edit
    @black_list = BlackList.find(params[:id])
  end

  # POST /black_lists
  # POST /black_lists.json
  def create
    @black_list = BlackList.new(params[:black_list])

    respond_to do |format|
      if @black_list.save
        format.html { redirect_to @black_list, :notice => 'Black list was successfully created.' }
        format.js {
          if request.env["HTTP_REFERER"].include? "locations"
            @location = @black_list.location
            render "/locations/update_blacklisttable"
          end
        }
        format.json { render :json => @black_list, :status => :created, :location => @black_list }
      else
        format.html { render :action => "new" }
        format.json { render :json => @black_list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /black_lists/1
  # PUT /black_lists/1.json
  def update
    @black_list = BlackList.find(params[:id])

    respond_to do |format|
      if @black_list.update_attributes(params[:black_list])
        format.html { redirect_to @black_list, :notice => 'Black list was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @black_list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /black_lists/1
  # DELETE /black_lists/1.json
  def destroy
    @black_list = BlackList.find(params[:id])
    @black_list.destroy

    respond_to do |format|
      format.html { redirect_to black_lists_url }
      format.js {
        if request.env["HTTP_REFERER"].include? "locations"
          @location = @black_list.location
          render "/locations/update_blacklisttable"
        end
      }
      format.json { head :ok }
    end
  end
end

app/helpers/black_lists_helper.rb
module BlackListsHelper
end

app/views/black_lists/_form.html.erb
<%= form_for(@black_list) do |f| %>
  <% if @black_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@black_list.errors.count, "error") %> prohibited this black_list from being saved:</h2>

      <ul>
      <% @black_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_id %><br />
    <%= f.number_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :song_id %><br />
    <%= f.number_field :song_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/black_lists/edit.html.erb
<h1>Editing black_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @black_list %> |
<%= link_to 'Back', black_lists_path %>

app/views/black_lists/index.html.erb
<h1>Listing black_lists</h1>

<table>
  <tr>
    <th>Location</th>
    <th>Song</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @black_lists.each do |black_list| %>
  <tr>
    <td><%= black_list.location_id %></td>
    <td><%= black_list.song_id %></td>
    <td><%= link_to 'Show', black_list %></td>
    <td><%= link_to 'Edit', edit_black_list_path(black_list) %></td>
    <td><%= link_to 'Destroy', black_list, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Black list', new_black_list_path %>

app/views/black_lists/new.html.erb
<h1>New black_list</h1>

<%= render 'form' %>

<%= link_to 'Back', black_lists_path %>

app/views/black_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Location:</b>
  <%= @black_list.location_id %>
</p>

<p>
  <b>Song:</b>
  <%= @black_list.song_id %>
</p>


<%= link_to 'Edit', edit_black_list_path(@black_list) %> |
<%= link_to 'Back', black_lists_path %>