config/routes.rb
Muzik::Application.routes.draw do

  resources :holiday_song_periods

  resources :media_players do
    collection do
      get 'datatable'
      get 'delete'
      get 'location_info'
      get 'songs_library'
      get 'blacklisted_songs'
      get 'playlists'
    end
  end

  resources :dashboard

  resources :playlists do
    collection do
      get 'display'
      get 'fetch'
    end
  end

  resources :energy_levels
  resources :energy_level_intervals

  resources :energy_level_wizard do
    collection do
      post 'add_energy_level_interval'
      post 'update_energy_level_intervals'
    end
  end

  resources :locations, :shallow => true do
    collection do
      get 'datatable'
      get 'delete'
      get 'blacklist_songs'
      post 'refresh_energy_level_intervals'
      get 'energy_level_intervals'
      get 'schedules'
    end
    resources :schedules
  end

  resources :black_lists do
    collection do
      get 'fetch'
    end
  end

  resources :group_song_assignments do
    collection do
      get 'upload_itunes_plist'
      post 'upload_itunes_plist'
    end
  end

  resources :song_libraries

  resources :groups do
    collection do
      get 'datatable'
      get 'remove_location'
      post 'add_location'
      get 'delete'
      get 'playlists'
      get 'songstable'
      get 'songs'
      get 'remove_group_song_assignment'
    end
  end

  resources :songs do
    collection do
      get 'upload'
      get 'datatable'
      get 'datatable2'
      get 'autocomplete_song_title'
      post 'add_tag'
    end
  end

  resources :taggings
  resources :tests

  root :to => 'dashboard#index'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :group
  validates :date, :uniqueness => {:scope => :group_id}
  def songs_list
    if content
      JSON.parse(content)
    else
      nil
    end
  end
  def songs_in_interval(start_time, end_time)
    songs = []
    if content
      songs_list.each do |song|
        songs << song if start_time <= song['timestamp'] && song['timestamp'] <= end_time
      end
    end
    songs
  end
  def songs_in_hour(hour)
    start_time = hour*60*60
    end_time = (hour + 1)*60*60
    songs_in_interval(start_time, end_time)
  end
end

app/controllers/playlists_controller.rb
require 'lib/playlist_generator'
class PlaylistsController < ApplicationController
  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @playlists }
    end
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @playlist }
    end
  end

  # GET /playlists/new
  # GET /playlists/new.json
  def new
    @playlist = Playlist.new(params[:playlist])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @playlist }
    end
  end

  # GET /playlists/1/edit
  def edit
    @playlist = Playlist.find(params[:id])
  end

  # POST /playlists
  # POST /playlists.json
  def create
    playlist = Playlist.new(params[:playlist])
    @group = Group.find(playlist.group_id)
    start_date = params[:start_date]
    end_date = params[:end_date]

    start_date = Date.parse(start_date)
    end_date = Date.parse(end_date)

    gen = PlaylistGenerator.new

    previous_playlist = Playlist.where(:group_id => @group.id, :date => start_date - 1).first

    @playlists = []
    success = true
    (start_date..end_date).each do |date|
      pl = Playlist.find_or_create_by_date_and_group_id(date, @group.id)
      logger.info "GOING TO GENERATE"
      songslist = gen.generate(@group, previous_playlist)

      unless songslist
        success = false
        break
      end
      pl.content = songslist.to_json
      pl.save
      @playlists << pl
      previous_playlist = @playlists[-1]
    end
    if !success
      render :text => "Failed to generate playlist. Most likely there isn't enough songs and/or rules are too restrictive."
      return
    end
  end

  # PUT /playlists/1
  # PUT /playlists/1.json
  def update
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      if @playlist.update_attributes(params[:playlist])
        format.html { redirect_to @playlist, :notice => 'Playlist was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @playlist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to playlists_url }
      format.json { head :ok }
    end
  end

  def fetch
    group_id = params[:group_id] || 1
    result = {}
    plists = Playlist.where(:group_id => group_id)
    plists.each do |pl|
      result[pl.date] = JSON.parse(pl.content)
    end
    respond_to do |format|
      format.html {
        render :text => result.inspect
      }
      format.json {
        render :json => result
      }
    end
  end
end

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <%= f.select :group_id, Group.order('name').collect{|g| [g.name, g.id]} %>
  from <%= text_field_tag :start_date, nil, :class => 'datetimefield'  %>
  to <%= text_field_tag :end_date , nil, :class => 'datetimefield'%>
  <%= submit_tag "Generate" %>
<% end %>

<script type="text/javascript">
  $(".datetimefield").AnyTime_picker({ format: "%M %D, %z", firstDOW: 1 } );
</script>

app/views/playlists/_songslist.html.erb
<script type="text/javascript">
  var oTable;
  $(document).ready(function() {
    oTable = $("#songslisttable<%= date %>").dataTable({
                                 "bJQueryUI"       : true,
                                 "bProcessing"     : false,
                                 "bServerSide"     : false,
                                 "aoColumnDefs"    : [{"bVisible":false, "aTargets":[0]}, {"bSortable":false, "aTargets":[1,2,3]}],
                                 "aaSorting"       : [[0, 'asc']]
                               });
  });
</script>

<table class="display" id="songslisttable<%= date %>">
  <thead>
  <tr>
    <th>sectime</th>
    <th>Time</th>
    <th>Title</th>
    <th>File</th>
  </tr>
  </thead>
  <tbody>
 <% songslist.each do |song| %>
  <tr>
    <td><%= song['timestamp'] %></td>
    <td><%= sec_to_human_time(song['timestamp']) %></td>
    <td><%= song['title'] %></td>
    <td><%= song['file_path'] %></td>
  </tr>
<% end %>
  </tbody>
</table>

app/views/playlists/create.html.erb
<% @playlists.each do |playlist| %>
  <b>Playlist for <%= playlist.group.name %> on <%= playlist.date %></b><br/>
  <div>
    <%= render :partial => 'songslist', :locals => {:songslist => playlist.songs_list, :date => playlist.date} %>
  </div>
  <br/>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/group_playlist.html.erb
<h3>Playlist for <%= @group.name %></h3>
<% @playlist.sort.each do |time, song| %>
  <%= Time.at(time.to_i).utc.strftime("%I:%M:%S %p") %> ==> <%= song.title %><br/>
<% end %>

app/views/playlists/index.html.erb
<h1>Listing playlists</h1>

<table>
  <tr>
    <th>Group</th>
    <th>Date</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @playlists.each do |playlist| %>
  <tr>
    <td><%= playlist.group_id %></td>
    <td><%= playlist.date %></td>
    <td><%= playlist.content %></td>
    <td><%= link_to 'Show', playlist %></td>
    <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
    <td><%= link_to 'Destroy', playlist, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Playlist', new_playlist_path %>

app/views/playlists/new.html.erb
<h1>New playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Group:</b>
  <%= @playlist.group_id %>
</p>

<p>
  <b>Date:</b>
  <%= @playlist.date %>
</p>

<div>
  <%= render :partial => 'songslist', :locals => {:songslist => @playlist.songs_list, :date => @playlist.date} %>
</div>