config/routes.rb
Muzik::Application.routes.draw do

  resources :holiday_song_periods

  resources :media_players do
    collection do
      get 'datatable'
      get 'delete'
      get 'location_info'
      get 'songs_library'
      get 'blacklisted_songs'
      get 'playlists'
    end
  end

  resources :dashboard

  resources :playlists do
    collection do
      get 'display'
      get 'fetch'
    end
  end

  resources :energy_levels
  resources :energy_level_intervals

  resources :energy_level_wizard do
    collection do
      post 'add_energy_level_interval'
      post 'update_energy_level_intervals'
    end
  end

  resources :locations, :shallow => true do
    collection do
      get 'datatable'
      get 'delete'
      get 'blacklist_songs'
      post 'refresh_energy_level_intervals'
      get 'energy_level_intervals'
      get 'schedules'
    end
    resources :schedules
  end

  resources :black_lists do
    collection do
      get 'fetch'
    end
  end

  resources :group_song_assignments do
    collection do
      get 'upload_itunes_plist'
      post 'upload_itunes_plist'
    end
  end

  resources :song_libraries

  resources :groups do
    collection do
      get 'datatable'
      get 'remove_location'
      post 'add_location'
      get 'delete'
      get 'playlists'
      get 'songstable'
      get 'songs'
      get 'remove_group_song_assignment'
    end
  end

  resources :songs do
    collection do
      get 'upload'
      get 'datatable'
      get 'datatable2'
      get 'autocomplete_song_title'
      post 'add_tag'
    end
  end

  resources :taggings
  resources :tests

  root :to => 'dashboard#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Muzik</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery-ui-timepicker-addon" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <style type="text/css">
    .ui-slider .ui-slider-handle { text-decoration:none; width: 35px;  height: 20px; background: #2F4D6D; margin-left: -15px; color: white; font-size:0.7em; text-align:center}
    .ui-slider { height: 15px; }
  </style>

  <div id="header">
    <h2>Music Manager</h2>
    <br/>
    <div id="layoutdims">
      Jump to:
      <%= link_to "Energy Levels", energy_levels_path %> |
      <%= link_to "Groups", groups_path %> |
      <%= link_to "Locations", locations_path %> |
      <%= link_to "Songs", songs_path %> |
      <%= link_to "Media Players", media_players_path %> |
      <!--
      <%= link_to "Playlist Generator", new_playlist_path %> |
      -->
      <%= link_to "Upload Songs List", "/group_song_assignments/upload_itunes_plist" %>
    </div>
  </div>
  <div class="colmask fullpage">
    <div class="col1">
    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>
    <%= yield %>
    </div>
  </div>

</body>
</html>